### ISSUE TITLE
Adapter Failed To Connect via Password

### ISSUE THREAD

**Issue by Keshav0690** [timescale/prometheus-postgresql-adapter#40]
Hi All,

I am trying to push the  prometheus data to postgresql via adapter. 

Issue: Adapter failing with password authentication error
Reason: I am using  kubernetes secret to hold the password in base 64 form. when fetching password via yaml and setting up it as env variable in k8s, the postgres adapter is not able to decode it because it seems adapter keep the password in single quotes and hence base64 is being treated as normal string.

Any help would be appreciated.

Regards,
Keshav Sharma

**Comment by niksajakovljevic** [comment]
Hi @Keshav0690 ,

as you might know Kubernetes encodes all secrets with Base64. One way to work around this is to define environment variable with your secret:

```
env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: pg-pass
```
This way env variable `PG_PASSWORD` will contain decoded password. You can use env variable in container arguments like:
```
args: ["-pg.password=$(PG_PASSWORD)"]
```
Hope this helps.
