### ISSUE TITLE
Docker image doesn't support leader-election flag

### ISSUE THREAD

**Issue by mcinquin** [timescale/prometheus-postgresql-adapter#62]
Hello,

Docker image doesn't support leader-election flag.

docker-compose.yml
```
version: '2.1'
services:
 prometheus_postgresql_adapter_1:
   image: timescale/prometheus-postgresql-adapter:master
   ports:
     - "9201:9201"
   command: "-pg.host=x.x.x.x -pg.prometheus-log-samples -leader-election.pg-advisory-lock-id=1 -leader-election.pg-advisory-lock.prometheus-timeout=6s"

 prometheus_postgresql_adapter_2:
   image: timescale/prometheus-postgresql-adapter:master
   ports:
     - "9202:9202"
   command: "-pg.host=x.x.x.x -pg.prometheus-log-samples -leader-election.pg-advisory-lock-id=1 -leader-election.pg-advisory-lock.prometheus-timeout=6s"
```

Logs:
```
...
prometheus_postgresql_adapter_1_1  | flag provided but not defined: -leader-election.pg-advisory-lock-id
...
prometheus_postgresql_adapter_2_1  | flag provided but not defined: -leader-election.pg-advisory-lock-id
...
```

Regards.
