### ISSUE TITLE
error: lookup pg_prometheus on <ip:port>: server misbehaving

### ISSUE THREAD

**Issue by kaytrance** [timescale/prometheus-postgresql-adapter#7]
I have this docker-compose file to start prometheus with this adapter:
```
version: "3.2"
volumes:
    prometheus_data: {}
services:

  # postgresql for prometheus
  pg_prometheus:
    image: timescale/pg_prometheus:master
    ports:
      - 5432:5432
    command:
      - 'postgres -csynchronous_commit=off'

  # storage adapter
  prometheus_postgresql_adapter:
    image: timescale/prometheus-postgresql-adapter:master
    ports:
      - 9201:9201
    links:
      - pg_prometheus
    depends_on:
      - pg_prometheus
    command:
      - '-pg-host=pg_prometheus'
      - '-pg-prometheus-log-samples'

  # prometheus 
  prometheus:
    image: prom/prometheus
    volumes:
      - type: bind
        source: ./configs/
        target: /etc/prometheus/
      - type: bind
        source: ./data
        target: /etc/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/data'
      - '--storage.tsdb.retention=31d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    depends_on:
      - pg_prometheus
      - prometheus_postgresql_adapter
    links:
      - prometheus_postgresql_adapter
```

In my `prometheus.yml` I added urls for reading and writing:
```
remote_write:
  - url: "http://prometheus_postgresql_adapter:9201/write"
remote_read:
  - url: "http://prometheus_postgresql_adapter:9201/read"
```

After I launch it I have the following log with errors:
```
Starting daedra_pg_prometheus_1 ... done
Recreating daedra_prometheus_postgresql_adapter_1 ... done
Recreating daedra_prometheus_1 ... done
Attaching to daedra_pg_prometheus_1, daedra_prometheus_postgresql_adapter_1, daedra_prometheus_1
pg_prometheus_1                  | /usr/local/bin/docker-entrypoint.sh: line 145: exec: postgres -csynchronous_commit=off: not found
prometheus_postgresql_adapter_1  | host=pg_prometheus port=5432 user=postgres dbname=postgres password='' sslmode=disable connect_timeout=10
daedra_pg_prometheus_1 exited with code 127
prometheus_1                     | level=info ts=2018-02-21T07:13:06.2090674Z caller=main.go:225 msg="Starting Prometheus" version="(version=2.1.0, branch=HEAD, revision=85f23d82a045d103ea7f3c89a91fba4a93e6367a)"
prometheus_1                     | level=info ts=2018-02-21T07:13:06.2118463Z caller=main.go:226 build_context="(go=go1.9.2, user=root@6e784304d3ff, date=20180119-12:01:23)"
prometheus_1                     | level=info ts=2018-02-21T07:13:06.2122849Z caller=main.go:227 host_details="(Linux 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 5e3d213d1b02 (none))"
prometheus_1                     | level=info ts=2018-02-21T07:13:06.2127513Z caller=main.go:228 fd_limits="(soft=1048576, hard=1048576)"
prometheus_1                     | level=info ts=2018-02-21T07:13:06.2159414Z caller=main.go:499 msg="Starting TSDB ..."
prometheus_1                     | level=info ts=2018-02-21T07:13:06.2159657Z caller=web.go:383 component=web msg="Start listening for connections" address=0.0.0.0:9090
prometheus_postgresql_adapter_1  | level=error ts=2018-02-21T07:13:07.5344368Z caller=client.go:99 err="dial tcp: lookup pg_prometheus on 127.0.0.11:53: server misbehaving"
prometheus_1                     | level=info ts=2018-02-21T07:13:07.969697Z caller=main.go:509 msg="TSDB started"
prometheus_1                     | level=info ts=2018-02-21T07:13:07.9697553Z caller=main.go:585 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
prometheus_1                     | level=info ts=2018-02-21T07:13:07.9818122Z caller=main.go:486 msg="Server is ready to receive web requests."
prometheus_1                     | level=info ts=2018-02-21T07:13:07.9818271Z caller=manager.go:59 component="scrape manager" msg="Starting scrape manager..."
daedra_prometheus_postgresql_adapter_1 exited with code 1
prometheus_1                     | level=error ts=2018-02-21T07:13:10.1086058Z caller=wal.go:709 component=tsdb msg="operation failed" err="sync WAL directory: sync /etc/prometheus/data/wal: invalid argument"
prometheus_1                     | level=warn ts=2018-02-21T07:13:11.1532438Z caller=queue_manager.go:485 component=remote msg="Error sending samples to remote storage" count=100 err="Post http://prometheus_postgresql_adapter:9201/write: dial tcp: lookup prometheus_postgresql_adapter on 127.0.0.11:53: server misbehaving"
prometheus_1                     | level=warn ts=2018-02-21T07:13:14.2745967Z caller=queue_manager.go:485 component=remote msg="Error sending samples to remote storage" count=100 err="Post http://prometheus_postgresql_adapter:9201/write: dial tcp: lookup prometheus_postgresql_adapter on 127.0.0.11:53: server misbehaving"
prometheus_1                     | level=warn ts=2018-02-21T07:13:17.4257119Z caller=queue_manager.go:485 component=remote msg="Error sending samples to remote storage" count=100 err="Post http://prometheus_postgresql_adapter:9201/write: dial tcp: lookup prometheus_postgresql_adapter on 127.0.0.11:53: server misbehaving"
```

Last line continues indefinitely.
What am I doing wrong?

**Comment by erimatnor** [comment]
@kaytrance The error seems to be in your PostgreSQL configuration, specifically the line `- 'postgres -csynchronous_commit=off'`, which I believe is interpreted as a single string/command. You need to split it in its component parts, like so:

```
command:
      - 'postgres'
      - '-csynchronous_commit=off'
```

**Comment by kaytrance** [comment]
That helped, thanks, however now when I try to bind folder where postgres stores data to a folder on my pc it complains that 
```
prometheus_postgresql_adapter_1  | level=error ts=2018-02-21T11:41:35.6487772Z caller=client.go:99 err="dial tcp 127.0.0.1:5432: getsockopt: connection refused"
```

Here's the config of a service:
```
  pg_prometheus:
    image: timescale/pg_prometheus:master
    ports:
      - 5432:5432
    command:
      - '-csynchronous_commit=off'
    volumes:
      - type: bind
        source: ./data_pg
        target: /tmp/data
    environment:
      PGDATA: /tmp/data
      POSTGRES_USER: postgres
    tty: true
```

if I try to bind `data_pg` straight away to `/var/lib/postgresql/data` it complains about duplicate mount.
